---
title: "MARINe sites: in situ temps report"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
source(here::here("functions.R"))
```

### In situ temperature

```{r}
# site_id <- "bra-arraialdocabo-fortaleza"
# site_id <- "bra-costadasalgas-gramute"
# site_id <- "usa-fknms"
# site_id <- "arg-puertomadryn3"
# site_id <- "usa-hop"
site_id <- "col-islagorgona-laventana" # new site

temp_csv <- here(glue("data_smoothed/{site_id}.csv"))
meta_yml <- here(glue("data_smoothed/{site_id}_meta.yml"))
site_url <- glue("https://raw.githubusercontent.com/marinebon/p2p/master/data/insitu_temp/{basename(temp_csv)}")

meta <- read_yaml(meta_yml)
d    <- read_csv(temp_csv)
x    <- xts(select(d, -day), order.by = d$day)

if (glue("{site_id}_zones.txt") %in% list.files(path = here("data_smoothed"))) {
  zones <- read_lines(here(glue("data_smoothed/{site_id}_zones.txt")))
  mins  <- glue("temp_c_min_{zones}")
  avgs  <- glue("temp_c_avg_{zones}")
  maxes <- glue("temp_c_max_{zones}")
}

# output timeseries plot
get_dygraph(x)
```

This timeseries was created using data collected by `r meta$num_loggers` biomimetic temperature loggers between `r min(d$day)` and `r max(d$day)`. Loggers were placed in the `r tolower(knitr::combine_words(names(x)))` zones of the intertidal ecosystem.

Download data: [`r basename(site_url)`](`r site_url`) 

